name: 'Debug'
description: 'Debug'
runs:
  using: composite
  steps:
    - id: debug
      name: debug
      shell: bash
      run: |
        echo action-env
        env
        echo
        echo 'objects...'

        cat <<<'EOF'
        github:
        ${{ toJSON(github) }}"

        env:
        ${{ toJSON(env) }}"

        job:
        ${{ toJSON(job) }}"

        jobs:
        {{ toJSON(jobs) }}"

        steps:
        ${{ toJSON(steps) }}"

        runner:
        ${{ toJSON(runner) }}"

        secrets:
        {{ toJSON(secrets) }}"

        strategy:
        ${{ toJSON(strategy) }}"

        matrix:
        ${{ toJSON(matrix) }}"

        needs:
        {{ toJSON(needs) }}"

        inputs:
        ${{ toJSON(inputs) }}"
        EOF
