name: 'Debug'
description: 'Debug'
runs:
  using: composite
  steps:
    - id: debug
      name: debug
      shell: bash
      run: |
        cat <<<'EOF'
        github:
        ${{ toJSON(github) }}"
        EOF
        cat <<<'EOF'
        env:
        ${{ toJSON(env) }}"
        EOF
        cat <<<'EOF'
        job:
        ${{ toJSON(job) }}"
        EOF
        cat <<<'EOF'
        jobs:
        {{ toJSON(jobs) }}"
        EOF
        cat <<<'EOF'
        steps:
        ${{ toJSON(steps) }}"
        EOF
        cat <<<'EOF'
        runner:
        ${{ toJSON(runner) }}"
        EOF
        cat <<<'EOF'
        secrets:
        {{ toJSON(secrets) }}"
        EOF
        cat <<<'EOF'
        strategy:
        ${{ toJSON(strategy) }}"
        EOF
        cat <<<'EOF'
        matrix:
        ${{ toJSON(matrix) }}"
        EOF
        cat <<<'EOF'
        needs:
        {{ toJSON(needs) }}"
        EOF
        cat <<<'EOF'
        inputs:
        ${{ toJSON(inputs) }}"
        echo action-env
        env
