name: 'Debug'
description: 'Debug'
runs:
  using: composite
  steps:
    - id: debug
      name: debug
      shell: bash
      env:
        x_env: ${{ toJSON(env || '') }}
        x_github: ${{ toJSON(github || '') }}
        x_job: ${{ toJSON(job || '') }}
        x_jobs: ${{ toJSON(jobs || '') }}
        x_secrets: ${{ toJSON(secrets || '') }}
        x_steps: ${{ toJSON(steps || '') }}
        x_runner: ${{ toJSON(runner || '') }}
        x_matrix: ${{ toJSON(matrix || '') }}
        x_needs: ${{ toJSON(needs || '') }}
        x_inputs: ${{ toJSON(inputs || '') }}
      run: |
        echo action-env
        env
        echo
        echo 'objects...'

        cat <<<'EOF'
        github:
        ${{ toJSON(github) }}"

        env:
        ${{ toJSON(env) }}"

        job:
        ${{ toJSON(job) }}"

        jobs:
        {{ toJSON(jobs) }}"

        steps:
        ${{ toJSON(steps) }}"

        runner:
        ${{ toJSON(runner) }}"

        secrets:
        {{ toJSON(secrets) }}"

        strategy:
        ${{ toJSON(strategy) }}"

        matrix:
        ${{ toJSON(matrix) }}"

        needs:
        {{ toJSON(needs) }}"

        inputs:
        ${{ toJSON(inputs) }}"
        EOF
